#============================================================================================================================|
#    _____                      .__      _________.__                        __________.__
#   /     \   _________________ |  |__  /   _____/|  |__   ____ ______  _____\______   \  |  __ __  ______
#  /  \ /  \ /  _ \_  __ \____ \|  |  \ \_____  \ |  |  \ /  _ \\____ \/  ___/|     ___/  | |  |  \/  ___/
# /    Y    (  <_> )  | \/  |_> >   Y  \/        \|   Y  (  <_> )  |_> >___ \ |    |   |  |_|  |  /\___ \
# \____|__  /\____/|__|  |   __/|___|  /_______  /|___|  /\____/|   __/____  >|____|   |____/____//____  >
#        \/             |__|        \/        \/      \/       |__|       \/                          \/
#============================================================================================================================|
#
# Author's Discord: Morphie#1738
# Spigot URL: TBA
#
#============================================================================================================================|

Settings:
  # Should the plugin automatically delete player data files within the ShopHistory/PlayerData files folder? (This system is in
  # place to help trim files of players who may never rejoin the server.)
  AutoDeletePlayerFiles:
    Enabled: false
    # Number of days a player has to be offline before attempting to remove their player file.
    DaysTillDeletion: 30

#============================================================================================================================|